export const BUTTON_INDEX_LAUNCH_CAMERA = 0;
export const BUTTON_INDEX_LAUNCH_IMAGE_LIBRARY = 1;
export const BUTTON_INDEX_CANCEL = 2;
export const UPLOAD_FILE_SIZE_LIMIT = 100;
export const MESSAGE_RESIZED_IMAGE_WIDTH = 1920;
export const MESSAGE_RESIZED_IMAGE_HEIGHT = 1920;

export const PROFILE_IMAGE_WIDTH = 1280;
export const PROFILE_IMAGE_HEIGHT = 1280;
