export const BUTTON_INDEX_LAUNCH_CAMERA = 0;
export const BUTTON_INDEX_LAUNCH_IMAGE_LIBRARY = 1;
export const BUTTON_INDEX_CANCEL = 2;

export const PROFILEIMAGE_WIDTH = 1280;
export const PROFILEIMAGE_HEIGHT = 1280;
