name: Deploy Website
on:
  push:
    branches:
      - master
    paths:
      - 'website/**'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 14.x

      - name: Install packages and build
        run: |
          pushd ./website
          yarn install --ignore-engines
          yarn build
          popd

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        run: |
          pushd ./website
          yarn install --ignore-engines
          yarn build
          popd

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          PERSONAL_TOKEN: ${{secrets.GH_TOKEN}}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./website/build
          SCRIPT_MODE: true

