name: Deploy Web App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./client

    steps:
    - uses: actions/checkout@v2

    - name: Install modules
      run: yarn

    - name: Install expo client
      run: yarn global add expo-cli

    - name: build web
      run: yarn predeploy
      env:
        GRAPHQL_URL: ${{ secrets.GRAPHQL_URL }}
        ROOT_URL: ${{ secrets.ROOT_URL }}
        facebookAppId: ${{ secrets.facebookAppId }}
        facebookSecret: ${{ secrets.facebookSecret }}
        googleClientId: ${{ secrets.googleClientId }}
        googleSecret: ${{ secrets.googleSecret }}

    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        PROJECT_PATH: ./client
 